# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: articles

jobs:
  articles:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "devtools", "tidyverse", "pkgdown"))
          remotes::install_deps(dependencies = TRUE)
          devtools::install()
        shell: Rscript {0}
      - name: Check
        run: |
          pkgdown::build_articles()
        shell: Rscript {0}
