# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "devtools", "tidyverse", "pkgdown"))
          devtools::install()
          devtools::install_deps(dependencies = 'suggests')
        shell: Rscript {0}
      - name: Check
        run: |
          pkgdown::build_articles()
          system("git clone https://github.com/erblast/parcats.git")
          devtools::install_deps('parcats/', dependencies = 'suggests')
          devtools::check('parcats/', error_on = 'note')
        shell: Rscript {0}
